### PR TITLE
Update build.gradle files to new Kotlin Multiplatform Gradle plugin

### PR DESCRIPTION
**Pull request by snrostov**
Use experimental Kotlin/JS plugin features create JS bundle.

Some caveats:
- Kotlin/JS plugin currently doesn't support production build variant, so DCE plugin currently not applied
- Question about packaging/running frontend into backend: we have 2 options:
  - The frontend can be started with its own HTTP dev server by running `./gradlew :frontend:run -t` (`web-dev-server` will be start). In this case, we need to configure the proxy to `api` and the backend should be started on another port.
  - Frontend can be packaged to backend jar, these lines do it: https://github.com/sdeleuze/spring-kotlin-fullstack/compare/master...snrostov:master#diff-65dbef115c0cbec8b8fca68319bcc9f8R37. But I'm not familiar with Spring Boot and I've got 404 on `https://localhost:8080/index.html` event it is in jar...

### CODE REVIEW

**Comment by sdeleuze** [comment]
Thank you so much, super helpful, I will continue to polish/maintain it.

**Comment by sdeleuze** [comment]
> Frontend can be packaged to backend jar, these lines do it: ...

@snrostov The link seems broken, could you provide me the right one?

**Comment by snrostov** [comment]
https://github.com/snrostov/spring-kotlin-fullstack/blob/faa41cb50d7c5b14842c0e7f02f5fe51a8d32cf2/backend/build.gradle.kts#L37-L43

**Comment by sdeleuze** [comment]
Fix via https://github.com/sdeleuze/spring-kotlin-fullstack/commit/ccc21fc2c049eedaae56736db88f19ad7fd84c04 (frontend assets need to go to `static`).

**Pull request merged**
